kind: pipeline
name: docker

trigger:
  branch:
    - dev

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/docker/distribution

clone:
  disable: true

steps:
  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY
        
  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.19-alpine
    settings:
      binary: registry
      main: cmd/registry

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/registry
      version: v2.8.1
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      repo: wod/registry
      version: v2.8.1
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-ppc64le
      repo: wod/registry
      version: v2.8.1
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-mips64le
      repo: wod/registry
      version: v2.8.1
      channel: mips64le
      args: 'TARGETOS=linux,TARGETARCH=mips64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/mips64le
      template: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8.1-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8.1
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: harbor-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8.1-amd64
      target: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8-amd64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8.1-arm64
      target: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8-arm64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8.1-ppc64le
      target: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8-ppc64le
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8.1-mips64le
      target: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8-mips64le
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/mips64le
      template: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/registry:v2.8
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets
