version: 0.1

log:
  level: debug
  accesslog:
    disabled: false
  fields:
    service: registry
    environment: development

storage:
  filesystem: {}

http:
  addr: :6444
  headers:
    X-Content-Type-Options: [nosniff]
